name: muhammed_s_application
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # SVG icon support
  flutter_svg: ^2.0.12

  # Feature dependencies - safe to modify
  cached_network_image: ^3.4.1

  # Shared preferences for storing user preferences
  shared_preferences: ^2.3.3

  # Get for state management
  get: ^4.6.6

  web: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
